// src/pages/Landing.vue
<template>
  <div class="min-h-screen bg-white">
    <!-- Top bar — Coursera / edX style -->
    <header
      class="fixed top-0 left-0 right-0 z-50 transition-all duration-500 ease-out"
      :class="
        scrolled
          ? 'bg-white/95 backdrop-blur-xl border-b border-gray-200/80 shadow-sm'
          : 'bg-transparent border-b border-transparent'
      "
    >
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-14 md:h-16 flex items-center justify-between">
        <RouterLink to="/" class="flex items-center gap-2.5 rounded-xl focus:outline-none focus-visible:ring-2 focus-visible:ring-white/80 focus-visible:ring-offset-2 focus-visible:ring-offset-blue-700">
          <div
            class="p-1.5 md:p-2 rounded-xl transition-all duration-300"
            :class="scrolled ? 'bg-gradient-to-br from-blue-600 to-blue-700 text-white shadow-md' : 'bg-white/20 text-white backdrop-blur-sm border border-white/25'"
          >
            <BookOpen class="w-5 h-5 md:w-6 md:h-6" />
          </div>
          <span class="text-base md:text-xl font-bold tracking-tight" :class="scrolled ? 'text-gray-900' : 'text-white drop-shadow-sm'">
            Bilim Merkezi
          </span>
        </RouterLink>
        <div class="flex items-center gap-2 md:gap-3">
          <RouterLink
            to="/login"
            class="px-3 md:px-4 py-2 text-sm md:text-base font-semibold rounded-xl transition-all duration-200 active:scale-[0.98]"
            :class="
              scrolled
                ? 'text-gray-700 hover:bg-gray-100'
                : 'text-white/95 hover:bg-white/15 border border-white/20'
            "
          >
            Giriş
          </RouterLink>
          <RouterLink
            to="/register"
            class="px-3 md:px-5 py-2 text-sm md:text-base font-semibold rounded-xl shadow-lg transition-all duration-200 active:scale-[0.98]"
            :class="
              scrolled
                ? 'bg-blue-600 text-white hover:bg-blue-700 shadow-blue-600/20'
                : 'bg-white text-blue-700 hover:bg-blue-50 shadow-black/10'
            "
          >
            Hasaba alyň
          </RouterLink>
        </div>
      </div>
    </header>

    <!-- Hero -->
    <section
      class="relative text-white overflow-hidden bm-hero-gradient bg-gradient-to-br from-[#0056d2] via-blue-700 to-indigo-900 pt-14 md:pt-16"
    >
      <div
        class="pointer-events-none absolute -top-24 -right-24 w-[min(100vw,28rem)] h-[min(100vw,28rem)] rounded-full bg-sky-400/25 blur-3xl bm-hero-blob"
      />
      <div
        class="pointer-events-none absolute top-1/2 -left-32 w-80 h-80 rounded-full bg-violet-500/20 blur-3xl bm-hero-blob bm-hero-blob-delay"
      />
      <div
        class="pointer-events-none absolute bottom-0 right-1/4 w-64 h-64 rounded-full bg-cyan-400/15 blur-3xl bm-hero-blob bm-hero-blob-delay-2"
      />
      <div class="absolute inset-0 bg-[radial-gradient(ellipse_80%_60%_at_50%_-20%,rgba(255,255,255,0.18),transparent)]" />
      <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 md:py-28 lg:py-32">
        <div
          class="text-center max-w-4xl mx-auto bm-stagger will-change-transform"
          :style="heroParallaxStyle"
        >
          <div
            class="inline-flex items-center gap-2 bg-white/15 backdrop-blur-md px-3 py-1.5 md:px-4 md:py-2 rounded-full mb-5 md:mb-6 border border-white/20"
          >
            <BookOpen class="w-4 h-4 md:w-5 md:h-5 flex-shrink-0" />
            <span class="text-xs md:text-sm font-medium">Türkmenistanyň iň öňdebaryjy onlaýn okuw platformasy</span>
          </div>
          <h1 class="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-extrabold mb-4 md:mb-6 leading-[1.1] tracking-tight">
            Geljegiňizi <br />
            <span class="text-blue-100">Döretmäge Başlaň</span>
          </h1>
          <p class="text-base sm:text-lg md:text-xl lg:text-2xl text-blue-50/95 mb-6 md:mb-8 leading-relaxed px-2 max-w-3xl mx-auto">
            22 sany hünär kurslary arkaly täze başarnyklary öwreniň.<br />
            Hünärmenlerden onlaýn okuw we resmi sertifikat alyň.
          </p>
          <div class="flex flex-col sm:flex-row gap-3 md:gap-4 justify-center px-4 sm:px-0">
            <RouterLink
              to="/register"
              class="inline-flex items-center justify-center gap-2 bg-white text-blue-700 px-6 py-3.5 md:px-8 md:py-4 rounded-xl font-bold text-base md:text-lg hover:bg-blue-50 transition-all duration-300 shadow-xl shadow-black/15 hover:shadow-2xl hover:-translate-y-0.5 active:translate-y-0"
            >
              Hasaba alyň <ArrowRight class="w-5 h-5" />
            </RouterLink>
            <RouterLink
              to="/login"
              class="inline-flex items-center justify-center gap-2 bg-white/10 backdrop-blur-md border-2 border-white/35 text-white px-6 py-3.5 md:px-8 md:py-4 rounded-xl font-bold text-base md:text-lg hover:bg-white/20 transition-all duration-300 active:scale-[0.99]"
            >
              Giriş
            </RouterLink>
          </div>
        </div>
      </div>
    </section>

    <!-- Features -->
    <section class="py-12 md:py-20">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div v-bm-reveal:up class="text-center mb-10 md:mb-16">
          <h2 class="text-2xl md:text-3xl lg:text-4xl font-extrabold text-gray-900 mb-3 md:mb-4 tracking-tight">Näme üçin bizi saýlamaly?</h2>
          <p class="text-base md:text-xl text-gray-600 max-w-2xl mx-auto">Häzirki zaman okuw usullary we tejribeli mugallymlar bilen bilim alyň</p>
        </div>
        <div class="grid grid-cols-1 sm:grid-cols-3 gap-5 md:gap-8">
          <div
            v-for="(f, idx) in features"
            :key="f.title"
            v-bm-reveal:up="idx * 100"
            class="group bg-white p-6 md:p-8 rounded-2xl border border-gray-100 shadow-sm hover:shadow-xl hover:border-blue-100 hover:-translate-y-1 transition-all duration-300"
          >
            <div
              :class="`w-10 h-10 md:w-12 md:h-12 ${f.bg} rounded-xl flex items-center justify-center mb-4 md:mb-6 transition-transform duration-300 group-hover:scale-110`"
            >
              <CheckCircle :class="`w-5 h-5 md:w-6 md:h-6 ${f.color}`" />
            </div>
            <h3 class="text-lg md:text-xl font-bold text-gray-900 mb-2 md:mb-3">{{ f.title }}</h3>
            <p class="text-sm md:text-base text-gray-600 leading-relaxed">{{ f.desc }}</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Categories -->
    <section class="py-12 md:py-20 bg-gradient-to-b from-slate-50 to-slate-100/80">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div v-bm-reveal:right class="text-center mb-10 md:mb-16">
          <h2 class="text-2xl md:text-3xl lg:text-4xl font-extrabold text-gray-900 mb-3 md:mb-4 tracking-tight">Kurs kategoriýalary</h2>
          <p class="text-base md:text-xl text-gray-600 max-w-2xl mx-auto">Dürli ugurlarda hünär kurslaryndan saýlaň</p>
        </div>
        <div class="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
          <div
            v-for="(cat, idx) in catList"
            :key="cat.name"
            v-bm-reveal:scale="idx * 70"
            class="bg-white p-4 md:p-6 rounded-2xl border border-gray-100 shadow-sm hover:shadow-lg hover:border-blue-100 transition-all duration-300 hover:-translate-y-1.5 cursor-default"
          >
            <div class="text-3xl md:text-4xl mb-3 md:mb-4 transition-transform duration-300 hover:scale-110 inline-block">{{ cat.icon }}</div>
            <h3 class="text-base md:text-xl font-bold text-gray-900 mb-1 md:mb-2">{{ cat.name }}</h3>
            <p class="text-sm md:text-base text-gray-600">{{ cat.count }} kurs</p>
          </div>
        </div>
      </div>
    </section>

    <!-- CTA -->
    <section class="py-14 md:py-20 relative overflow-hidden bg-gradient-to-br from-[#0056d2] to-indigo-900 text-white">
      <div class="absolute inset-0 opacity-30 bg-[radial-gradient(circle_at_30%_20%,white,transparent_50%)]" />
      <div v-bm-reveal:scale class="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <h2 class="text-2xl md:text-3xl lg:text-4xl font-extrabold mb-4 md:mb-6 tracking-tight">Bilim syýahatyňyza häzir başlaň!</h2>
        <p class="text-base md:text-xl text-blue-100 mb-6 md:mb-8">Mugt hasaba alnyň we 22 sany hünär kursyna giriň</p>
        <RouterLink
          to="/register"
          class="inline-flex items-center gap-2 bg-white text-blue-700 px-6 py-3.5 md:px-8 md:py-4 rounded-xl font-bold text-base md:text-lg hover:bg-blue-50 transition-all duration-300 shadow-xl hover:shadow-2xl hover:-translate-y-0.5 active:translate-y-0"
        >
          Mugt hasaba alyň <ArrowRight class="w-5 h-5" />
        </RouterLink>
      </div>
    </section>

    <AppFooter />
  </div>
</template>

<script setup>
import { ref, inject, watch, computed, onMounted, onUnmounted } from 'vue'
import { BookOpen, CheckCircle, ArrowRight } from 'lucide-vue-next'
import AppFooter from '../components/AppFooter.vue'

const bmLenis = inject('bmLenis')
const scrolled = ref(false)
const scrollY = ref(0)
let offParallax = () => {}

const heroParallaxStyle = computed(() => ({
  transform: `translate3d(0, ${Math.min(scrollY.value * 0.08, 52)}px, 0)`,
}))

function bindParallax() {
  offParallax()
  const L = bmLenis.value
  if (L) {
    offParallax = L.on('scroll', inst => {
      scrollY.value = inst.scroll
    })
    scrollY.value = L.scroll
  } else {
    const w = () => {
      scrollY.value = window.scrollY
    }
    window.addEventListener('scroll', w, { passive: true })
    offParallax = () => window.removeEventListener('scroll', w)
    w()
  }
}

watch(bmLenis, bindParallax, { immediate: true })

function onScroll() {
  scrolled.value = window.scrollY > 24
}

onMounted(() => {
  onScroll()
  window.addEventListener('scroll', onScroll, { passive: true })
})

onUnmounted(() => {
  offParallax()
  window.removeEventListener('scroll', onScroll)
})

const features = [
  { title: 'Hünärmen mugallymlar', desc: 'Tejribeli we bilimli mugallymlardan sapak alyň. Her mugallym öz ugrunda hünärmendir.', bg: 'bg-blue-100', color: 'text-blue-600' },
  { title: 'Amaly tejribe', desc: 'Nazaryýet bilen bir hatarda amaly meşgullenmeler we taslamalar arkaly öwreniň.', bg: 'bg-green-100', color: 'text-green-600' },
  { title: 'Resmi sertifikat', desc: 'Kursy üstünlikli tamamlanyňyzdan soň resmi ykrar edilen sertifikat alyň.', bg: 'bg-purple-100', color: 'text-purple-600' },
]

const catList = [
  { name: 'Programirlemek', count: 11, icon: '💻' },
  { name: 'Daşary ýurt dilleri', count: 5, icon: '🗣️' },
  { name: 'Ylymlar', count: 3, icon: '🔬' },
  { name: 'Matematika', count: 1, icon: '🔢' },
  { name: 'Mugallymçylyk', count: 1, icon: '👨‍🏫' },
  { name: 'Kompýuter endikleri', count: 1, icon: '🖥️' },
]

const footerLinks = [
  { to: '/', label: 'Baş Sahypa' },
  { to: '/courses', label: 'Kurslar' },
  { to: '/login', label: 'Giriş' },
  { to: '/register', label: 'Hasaba alyň' },
]
</script>

// zip_extracted/src/app/pages/Landing.tsx
import { Link } from 'react-router';
import { BookOpen, Users, Award, Clock, CheckCircle, ArrowRight } from 'lucide-react';
import { ImageWithFallback } from '../components/figma/ImageWithFallback';

export function Landing() {
  return (
    <div className="min-h-screen bg-white">
      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-blue-600 via-blue-700 to-blue-900 text-white overflow-hidden">
        <div className="absolute inset-0 bg-black opacity-10"></div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 md:py-32">
          <div className="text-center max-w-4xl mx-auto">
            <div className="inline-flex items-center gap-2 bg-white/20 backdrop-blur-sm px-4 py-2 rounded-full mb-6">
              <BookOpen className="w-5 h-5" />
              <span className="text-sm font-medium">Türkmenistanyň iň öňdebaryjy onlaýn okuw platformasy</span>
            </div>
            
            <h1 className="text-4xl md:text-6xl font-bold mb-6">
              Geljekiňizi häzir
              <br />
              <span className="text-blue-200">Döretmäge Başlaň</span>
            </h1>
            
            <p className="text-xl md:text-2xl text-blue-100 mb-8 leading-relaxed">
              22 sany hünär kurslary arkaly täze başarnyklary öwreniň.
              <br />
              Hünärmenlerden onlaýn okuw we resmi sertifikat alyň.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                to="/register"
                className="inline-flex items-center justify-center gap-2 bg-white text-blue-600 px-8 py-4 rounded-lg font-semibold text-lg hover:bg-blue-50 transition-all shadow-lg hover:shadow-xl"
              >
                Hasaba alyň
                <ArrowRight className="w-5 h-5" />
              </Link>
              <Link
                to="/login"
                className="inline-flex items-center justify-center gap-2 bg-blue-500/30 backdrop-blur-sm border-2 border-white/30 text-white px-8 py-4 rounded-lg font-semibold text-lg hover:bg-blue-500/40 transition-all"
              >
                Giriş
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-16 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div className="text-center">
              <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-100 rounded-full mb-4">
                <BookOpen className="w-8 h-8 text-blue-600" />
              </div>
              <p className="text-4xl font-bold text-gray-900 mb-2">22</p>
              <p className="text-gray-600">Hünär kurslary</p>
            </div>
            
            <div className="text-center">
              <div className="inline-flex items-center justify-center w-16 h-16 bg-green-100 rounded-full mb-4">
                <Users className="w-8 h-8 text-green-600" />
              </div>
              <p className="text-4xl font-bold text-gray-900 mb-2">5000+</p>
              <p className="text-gray-600">Aktiwçi okuwçylar</p>
            </div>
            
            <div className="text-center">
              <div className="inline-flex items-center justify-center w-16 h-16 bg-purple-100 rounded-full mb-4">
                <Award className="w-8 h-8 text-purple-600" />
              </div>
              <p className="text-4xl font-bold text-gray-900 mb-2">95%</p>
              <p className="text-gray-600">Üstünlik derejesi</p>
            </div>
            
            <div className="text-center">
              <div className="inline-flex items-center justify-center w-16 h-16 bg-orange-100 rounded-full mb-4">
                <Clock className="w-8 h-8 text-orange-600" />
              </div>
              <p className="text-4xl font-bold text-gray-900 mb-2">24/7</p>
              <p className="text-gray-600">Elýeterli okuw</p>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Näme üçin bizi saýlamaly?
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Häzirki zaman okuw usullary we tejribeli mugallymlar bilen bilim alyň
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-white p-8 rounded-xl shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-6">
                <CheckCircle className="w-6 h-6 text-blue-600" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-3">
                Hünärmen mugallymlar
              </h3>
              <p className="text-gray-600 leading-relaxed">
                Tejribeli we bilimli mugallymlardan sapak alyň. Her mugallym öz ugrunda hünärmendir.
              </p>
            </div>

            <div className="bg-white p-8 rounded-xl shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mb-6">
                <CheckCircle className="w-6 h-6 text-green-600" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-3">
                Amaly tejribe
              </h3>
              <p className="text-gray-600 leading-relaxed">
                Nazaryýet bilen bir hatarda amaly meşgullenmeler we taslamalar arkaly öwreniň.
              </p>
            </div>

            <div className="bg-white p-8 rounded-xl shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
              <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mb-6">
                <CheckCircle className="w-6 h-6 text-purple-600" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-3">
                Resmi sertifikat
              </h3>
              <p className="text-gray-600 leading-relaxed">
                Kursy üstünlikli tamamlanyňyzdan soň resmi ykrar edilen sertifikat alyň.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Courses Preview */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Kurs kategoriýalary
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Dürli ugurlarda hünär kurslaryndan saýlaň
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[
              { name: 'Programirlemek', count: 11, icon: '💻', color: 'blue' },
              { name: 'Daşary ýurt dilleri', count: 5, icon: '🗣️', color: 'green' },
              { name: 'Ylymlar', count: 3, icon: '🔬', color: 'purple' },
              { name: 'Matematika', count: 1, icon: '🔢', color: 'orange' },
              { name: 'Mugallymçylyk', count: 1, icon: '👨‍🏫', color: 'red' },
              { name: 'Kompýuter endikleri', count: 1, icon: '🖥️', color: 'indigo' },
            ].map((category) => (
              <div
                key={category.name}
                className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 hover:shadow-md transition-all hover:-translate-y-1"
              >
                <div className="text-4xl mb-4">{category.icon}</div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">
                  {category.name}
                </h3>
                <p className="text-gray-600">{category.count} kurs</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-br from-blue-600 to-blue-800 text-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-6">
            Bilim syýahatyňyzy häzir başlaň!
          </h2>
          <p className="text-xl text-blue-100 mb-8">
            Mugt hasaba alnyň we 22 sany hünär kursyna giriň
          </p>
          <Link
            to="/register"
            className="inline-flex items-center gap-2 bg-white text-blue-600 px-8 py-4 rounded-lg font-semibold text-lg hover:bg-blue-50 transition-all shadow-lg"
          >
            Mugt hasaba alyň
            <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-300 py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <div className="flex items-center justify-center gap-2 mb-4">
              <div className="bg-blue-600 text-white p-2 rounded-lg">
                <BookOpen className="w-6 h-6" />
              </div>
              <span className="text-xl font-semibold text-white">Bilim Merkezi</span>
            </div>
            <p className="text-gray-400">
              © 2026 Bilim Merkezi. Ähli hukuklar goragly.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
